import { Metadata } from "next";
import "./globals.css";
import { Rambla } from "next/font/google";

const rambla = Rambla({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "| Mercado Livre 📦",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="" lang="PT-BR" suppressHydrationWarning>
      <body className={rambla.className}>{children}</body>
    </html>
  );
}
